/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InscricaoTokenRouteImport } from './routes/inscricao.$token'
import { Route as CalculadoraPropostaTokenRouteImport } from './routes/calculadora-proposta.$token'
import { Route as BugsTokenRouteImport } from './routes/bugs.$token'
import { Route as AuthenticatedTimeRouteImport } from './routes/_authenticated/time'
import { Route as AuthenticatedPrimeiroAcessoRouteImport } from './routes/_authenticated/primeiro-acesso'
import { Route as AuthenticatedFocoRouteImport } from './routes/_authenticated/foco'
import { Route as AuthenticatedDesignSystemFinanceConceptRouteImport } from './routes/_authenticated/design-system-finance-concept'
import { Route as AuthenticatedDesignSystemRouteImport } from './routes/_authenticated/design-system'
import { Route as PortalTokenRouteRouteImport } from './routes/portal.$token/route'
import { Route as PortalTokenIndexRouteImport } from './routes/portal.$token/index'
import { Route as PortalTokenSolicitacoesRouteImport } from './routes/portal.$token/solicitacoes'
import { Route as PortalTokenRelatoriosRouteImport } from './routes/portal.$token/relatorios'
import { Route as PortalTokenInicioRouteImport } from './routes/portal.$token/inicio'
import { Route as PortalTokenAprovacoesRouteImport } from './routes/portal.$token/aprovacoes'
import { Route as EmailDescadastroTokenRouteImport } from './routes/email.descadastro.$token'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks/resend'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiGoogleOauthCallbackRouteImport } from './routes/api/google/oauth-callback'
import { Route as ApiCronHypitoWeeklyReportRouteImport } from './routes/api/cron/hypito-weekly-report'
import { Route as ApiCronHypitoDailyBriefingRouteImport } from './routes/api/cron/hypito-daily-briefing'
import { Route as ApiCronHypitoAlertsRouteImport } from './routes/api/cron/hypito-alerts'
import { Route as ApiCronEmailFlowsRouteImport } from './routes/api/cron/email-flows'
import { Route as AuthenticatedProjetoIdRouteImport } from './routes/_authenticated/projeto.$id'
import { Route as PortalTokenCampanhasIndexRouteImport } from './routes/portal.$token/campanhas.index'
import { Route as PortalTokenCampanhasCampanhaIdRouteImport } from './routes/portal.$token/campanhas.$campanhaId'
import { Route as PortalTokenCampanhasCampanhaIdAprovacoesRouteImport } from './routes/portal.$token/campanhas.$campanhaId.aprovacoes'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoTokenRoute = InscricaoTokenRouteImport.update({
  id: '/inscricao/$token',
  path: '/inscricao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraPropostaTokenRoute =
  CalculadoraPropostaTokenRouteImport.update({
    id: '/calculadora-proposta/$token',
    path: '/calculadora-proposta/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const BugsTokenRoute = BugsTokenRouteImport.update({
  id: '/bugs/$token',
  path: '/bugs/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimeRoute = AuthenticatedTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrimeiroAcessoRoute =
  AuthenticatedPrimeiroAcessoRouteImport.update({
    id: '/primeiro-acesso',
    path: '/primeiro-acesso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFocoRoute = AuthenticatedFocoRouteImport.update({
  id: '/foco',
  path: '/foco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignSystemFinanceConceptRoute =
  AuthenticatedDesignSystemFinanceConceptRouteImport.update({
    id: '/design-system-finance-concept',
    path: '/design-system-finance-concept',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesignSystemRoute =
  AuthenticatedDesignSystemRouteImport.update({
    id: '/design-system',
    path: '/design-system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PortalTokenRouteRoute = PortalTokenRouteRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenIndexRoute = PortalTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTokenRouteRoute,
} as any)
const PortalTokenSolicitacoesRoute = PortalTokenSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => PortalTokenRouteRoute,
} as any)
const PortalTokenRelatoriosRoute = PortalTokenRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PortalTokenRouteRoute,
} as any)
const PortalTokenInicioRoute = PortalTokenInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => PortalTokenRouteRoute,
} as any)
const PortalTokenAprovacoesRoute = PortalTokenAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => PortalTokenRouteRoute,
} as any)
const EmailDescadastroTokenRoute = EmailDescadastroTokenRouteImport.update({
  id: '/email/descadastro/$token',
  path: '/email/descadastro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleOauthCallbackRoute = ApiGoogleOauthCallbackRouteImport.update({
  id: '/api/google/oauth-callback',
  path: '/api/google/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronHypitoWeeklyReportRoute =
  ApiCronHypitoWeeklyReportRouteImport.update({
    id: '/api/cron/hypito-weekly-report',
    path: '/api/cron/hypito-weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronHypitoDailyBriefingRoute =
  ApiCronHypitoDailyBriefingRouteImport.update({
    id: '/api/cron/hypito-daily-briefing',
    path: '/api/cron/hypito-daily-briefing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronHypitoAlertsRoute = ApiCronHypitoAlertsRouteImport.update({
  id: '/api/cron/hypito-alerts',
  path: '/api/cron/hypito-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEmailFlowsRoute = ApiCronEmailFlowsRouteImport.update({
  id: '/api/cron/email-flows',
  path: '/api/cron/email-flows',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetoIdRoute = AuthenticatedProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalTokenCampanhasIndexRoute =
  PortalTokenCampanhasIndexRouteImport.update({
    id: '/campanhas/',
    path: '/campanhas/',
    getParentRoute: () => PortalTokenRouteRoute,
  } as any)
const PortalTokenCampanhasCampanhaIdRoute =
  PortalTokenCampanhasCampanhaIdRouteImport.update({
    id: '/campanhas/$campanhaId',
    path: '/campanhas/$campanhaId',
    getParentRoute: () => PortalTokenRouteRoute,
  } as any)
const PortalTokenCampanhasCampanhaIdAprovacoesRoute =
  PortalTokenCampanhasCampanhaIdAprovacoesRouteImport.update({
    id: '/aprovacoes',
    path: '/aprovacoes',
    getParentRoute: () => PortalTokenCampanhasCampanhaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal/$token': typeof PortalTokenRouteRouteWithChildren
  '/design-system': typeof AuthenticatedDesignSystemRoute
  '/design-system-finance-concept': typeof AuthenticatedDesignSystemFinanceConceptRoute
  '/foco': typeof AuthenticatedFocoRoute
  '/primeiro-acesso': typeof AuthenticatedPrimeiroAcessoRoute
  '/time': typeof AuthenticatedTimeRoute
  '/bugs/$token': typeof BugsTokenRoute
  '/calculadora-proposta/$token': typeof CalculadoraPropostaTokenRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/cron/email-flows': typeof ApiCronEmailFlowsRoute
  '/api/cron/hypito-alerts': typeof ApiCronHypitoAlertsRoute
  '/api/cron/hypito-daily-briefing': typeof ApiCronHypitoDailyBriefingRoute
  '/api/cron/hypito-weekly-report': typeof ApiCronHypitoWeeklyReportRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/email/descadastro/$token': typeof EmailDescadastroTokenRoute
  '/portal/$token/aprovacoes': typeof PortalTokenAprovacoesRoute
  '/portal/$token/inicio': typeof PortalTokenInicioRoute
  '/portal/$token/relatorios': typeof PortalTokenRelatoriosRoute
  '/portal/$token/solicitacoes': typeof PortalTokenSolicitacoesRoute
  '/portal/$token/': typeof PortalTokenIndexRoute
  '/portal/$token/campanhas/$campanhaId': typeof PortalTokenCampanhasCampanhaIdRouteWithChildren
  '/portal/$token/campanhas/': typeof PortalTokenCampanhasIndexRoute
  '/portal/$token/campanhas/$campanhaId/aprovacoes': typeof PortalTokenCampanhasCampanhaIdAprovacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof AuthenticatedDesignSystemRoute
  '/design-system-finance-concept': typeof AuthenticatedDesignSystemFinanceConceptRoute
  '/foco': typeof AuthenticatedFocoRoute
  '/primeiro-acesso': typeof AuthenticatedPrimeiroAcessoRoute
  '/time': typeof AuthenticatedTimeRoute
  '/bugs/$token': typeof BugsTokenRoute
  '/calculadora-proposta/$token': typeof CalculadoraPropostaTokenRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/cron/email-flows': typeof ApiCronEmailFlowsRoute
  '/api/cron/hypito-alerts': typeof ApiCronHypitoAlertsRoute
  '/api/cron/hypito-daily-briefing': typeof ApiCronHypitoDailyBriefingRoute
  '/api/cron/hypito-weekly-report': typeof ApiCronHypitoWeeklyReportRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/email/descadastro/$token': typeof EmailDescadastroTokenRoute
  '/portal/$token/aprovacoes': typeof PortalTokenAprovacoesRoute
  '/portal/$token/inicio': typeof PortalTokenInicioRoute
  '/portal/$token/relatorios': typeof PortalTokenRelatoriosRoute
  '/portal/$token/solicitacoes': typeof PortalTokenSolicitacoesRoute
  '/portal/$token': typeof PortalTokenIndexRoute
  '/portal/$token/campanhas/$campanhaId': typeof PortalTokenCampanhasCampanhaIdRouteWithChildren
  '/portal/$token/campanhas': typeof PortalTokenCampanhasIndexRoute
  '/portal/$token/campanhas/$campanhaId/aprovacoes': typeof PortalTokenCampanhasCampanhaIdAprovacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/portal/$token': typeof PortalTokenRouteRouteWithChildren
  '/_authenticated/design-system': typeof AuthenticatedDesignSystemRoute
  '/_authenticated/design-system-finance-concept': typeof AuthenticatedDesignSystemFinanceConceptRoute
  '/_authenticated/foco': typeof AuthenticatedFocoRoute
  '/_authenticated/primeiro-acesso': typeof AuthenticatedPrimeiroAcessoRoute
  '/_authenticated/time': typeof AuthenticatedTimeRoute
  '/bugs/$token': typeof BugsTokenRoute
  '/calculadora-proposta/$token': typeof CalculadoraPropostaTokenRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/_authenticated/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/cron/email-flows': typeof ApiCronEmailFlowsRoute
  '/api/cron/hypito-alerts': typeof ApiCronHypitoAlertsRoute
  '/api/cron/hypito-daily-briefing': typeof ApiCronHypitoDailyBriefingRoute
  '/api/cron/hypito-weekly-report': typeof ApiCronHypitoWeeklyReportRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/email/descadastro/$token': typeof EmailDescadastroTokenRoute
  '/portal/$token/aprovacoes': typeof PortalTokenAprovacoesRoute
  '/portal/$token/inicio': typeof PortalTokenInicioRoute
  '/portal/$token/relatorios': typeof PortalTokenRelatoriosRoute
  '/portal/$token/solicitacoes': typeof PortalTokenSolicitacoesRoute
  '/portal/$token/': typeof PortalTokenIndexRoute
  '/portal/$token/campanhas/$campanhaId': typeof PortalTokenCampanhasCampanhaIdRouteWithChildren
  '/portal/$token/campanhas/': typeof PortalTokenCampanhasIndexRoute
  '/portal/$token/campanhas/$campanhaId/aprovacoes': typeof PortalTokenCampanhasCampanhaIdAprovacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal/$token'
    | '/design-system'
    | '/design-system-finance-concept'
    | '/foco'
    | '/primeiro-acesso'
    | '/time'
    | '/bugs/$token'
    | '/calculadora-proposta/$token'
    | '/inscricao/$token'
    | '/projeto/$id'
    | '/api/cron/email-flows'
    | '/api/cron/hypito-alerts'
    | '/api/cron/hypito-daily-briefing'
    | '/api/cron/hypito-weekly-report'
    | '/api/google/oauth-callback'
    | '/api/public/leads'
    | '/api/webhooks/resend'
    | '/email/descadastro/$token'
    | '/portal/$token/aprovacoes'
    | '/portal/$token/inicio'
    | '/portal/$token/relatorios'
    | '/portal/$token/solicitacoes'
    | '/portal/$token/'
    | '/portal/$token/campanhas/$campanhaId'
    | '/portal/$token/campanhas/'
    | '/portal/$token/campanhas/$campanhaId/aprovacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/design-system-finance-concept'
    | '/foco'
    | '/primeiro-acesso'
    | '/time'
    | '/bugs/$token'
    | '/calculadora-proposta/$token'
    | '/inscricao/$token'
    | '/projeto/$id'
    | '/api/cron/email-flows'
    | '/api/cron/hypito-alerts'
    | '/api/cron/hypito-daily-briefing'
    | '/api/cron/hypito-weekly-report'
    | '/api/google/oauth-callback'
    | '/api/public/leads'
    | '/api/webhooks/resend'
    | '/email/descadastro/$token'
    | '/portal/$token/aprovacoes'
    | '/portal/$token/inicio'
    | '/portal/$token/relatorios'
    | '/portal/$token/solicitacoes'
    | '/portal/$token'
    | '/portal/$token/campanhas/$campanhaId'
    | '/portal/$token/campanhas'
    | '/portal/$token/campanhas/$campanhaId/aprovacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/portal/$token'
    | '/_authenticated/design-system'
    | '/_authenticated/design-system-finance-concept'
    | '/_authenticated/foco'
    | '/_authenticated/primeiro-acesso'
    | '/_authenticated/time'
    | '/bugs/$token'
    | '/calculadora-proposta/$token'
    | '/inscricao/$token'
    | '/_authenticated/projeto/$id'
    | '/api/cron/email-flows'
    | '/api/cron/hypito-alerts'
    | '/api/cron/hypito-daily-briefing'
    | '/api/cron/hypito-weekly-report'
    | '/api/google/oauth-callback'
    | '/api/public/leads'
    | '/api/webhooks/resend'
    | '/email/descadastro/$token'
    | '/portal/$token/aprovacoes'
    | '/portal/$token/inicio'
    | '/portal/$token/relatorios'
    | '/portal/$token/solicitacoes'
    | '/portal/$token/'
    | '/portal/$token/campanhas/$campanhaId'
    | '/portal/$token/campanhas/'
    | '/portal/$token/campanhas/$campanhaId/aprovacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortalTokenRouteRoute: typeof PortalTokenRouteRouteWithChildren
  BugsTokenRoute: typeof BugsTokenRoute
  CalculadoraPropostaTokenRoute: typeof CalculadoraPropostaTokenRoute
  InscricaoTokenRoute: typeof InscricaoTokenRoute
  ApiCronEmailFlowsRoute: typeof ApiCronEmailFlowsRoute
  ApiCronHypitoAlertsRoute: typeof ApiCronHypitoAlertsRoute
  ApiCronHypitoDailyBriefingRoute: typeof ApiCronHypitoDailyBriefingRoute
  ApiCronHypitoWeeklyReportRoute: typeof ApiCronHypitoWeeklyReportRoute
  ApiGoogleOauthCallbackRoute: typeof ApiGoogleOauthCallbackRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
  EmailDescadastroTokenRoute: typeof EmailDescadastroTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$token': {
      id: '/inscricao/$token'
      path: '/inscricao/$token'
      fullPath: '/inscricao/$token'
      preLoaderRoute: typeof InscricaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-proposta/$token': {
      id: '/calculadora-proposta/$token'
      path: '/calculadora-proposta/$token'
      fullPath: '/calculadora-proposta/$token'
      preLoaderRoute: typeof CalculadoraPropostaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs/$token': {
      id: '/bugs/$token'
      path: '/bugs/$token'
      fullPath: '/bugs/$token'
      preLoaderRoute: typeof BugsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/time': {
      id: '/_authenticated/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthenticatedTimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/primeiro-acesso': {
      id: '/_authenticated/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof AuthenticatedPrimeiroAcessoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foco': {
      id: '/_authenticated/foco'
      path: '/foco'
      fullPath: '/foco'
      preLoaderRoute: typeof AuthenticatedFocoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design-system-finance-concept': {
      id: '/_authenticated/design-system-finance-concept'
      path: '/design-system-finance-concept'
      fullPath: '/design-system-finance-concept'
      preLoaderRoute: typeof AuthenticatedDesignSystemFinanceConceptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design-system': {
      id: '/_authenticated/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AuthenticatedDesignSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token/': {
      id: '/portal/$token/'
      path: '/'
      fullPath: '/portal/$token/'
      preLoaderRoute: typeof PortalTokenIndexRouteImport
      parentRoute: typeof PortalTokenRouteRoute
    }
    '/portal/$token/solicitacoes': {
      id: '/portal/$token/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/portal/$token/solicitacoes'
      preLoaderRoute: typeof PortalTokenSolicitacoesRouteImport
      parentRoute: typeof PortalTokenRouteRoute
    }
    '/portal/$token/relatorios': {
      id: '/portal/$token/relatorios'
      path: '/relatorios'
      fullPath: '/portal/$token/relatorios'
      preLoaderRoute: typeof PortalTokenRelatoriosRouteImport
      parentRoute: typeof PortalTokenRouteRoute
    }
    '/portal/$token/inicio': {
      id: '/portal/$token/inicio'
      path: '/inicio'
      fullPath: '/portal/$token/inicio'
      preLoaderRoute: typeof PortalTokenInicioRouteImport
      parentRoute: typeof PortalTokenRouteRoute
    }
    '/portal/$token/aprovacoes': {
      id: '/portal/$token/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/portal/$token/aprovacoes'
      preLoaderRoute: typeof PortalTokenAprovacoesRouteImport
      parentRoute: typeof PortalTokenRouteRoute
    }
    '/email/descadastro/$token': {
      id: '/email/descadastro/$token'
      path: '/email/descadastro/$token'
      fullPath: '/email/descadastro/$token'
      preLoaderRoute: typeof EmailDescadastroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/oauth-callback': {
      id: '/api/google/oauth-callback'
      path: '/api/google/oauth-callback'
      fullPath: '/api/google/oauth-callback'
      preLoaderRoute: typeof ApiGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/hypito-weekly-report': {
      id: '/api/cron/hypito-weekly-report'
      path: '/api/cron/hypito-weekly-report'
      fullPath: '/api/cron/hypito-weekly-report'
      preLoaderRoute: typeof ApiCronHypitoWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/hypito-daily-briefing': {
      id: '/api/cron/hypito-daily-briefing'
      path: '/api/cron/hypito-daily-briefing'
      fullPath: '/api/cron/hypito-daily-briefing'
      preLoaderRoute: typeof ApiCronHypitoDailyBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/hypito-alerts': {
      id: '/api/cron/hypito-alerts'
      path: '/api/cron/hypito-alerts'
      fullPath: '/api/cron/hypito-alerts'
      preLoaderRoute: typeof ApiCronHypitoAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/email-flows': {
      id: '/api/cron/email-flows'
      path: '/api/cron/email-flows'
      fullPath: '/api/cron/email-flows'
      preLoaderRoute: typeof ApiCronEmailFlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projeto/$id': {
      id: '/_authenticated/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof AuthenticatedProjetoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/$token/campanhas/': {
      id: '/portal/$token/campanhas/'
      path: '/campanhas'
      fullPath: '/portal/$token/campanhas/'
      preLoaderRoute: typeof PortalTokenCampanhasIndexRouteImport
      parentRoute: typeof PortalTokenRouteRoute
    }
    '/portal/$token/campanhas/$campanhaId': {
      id: '/portal/$token/campanhas/$campanhaId'
      path: '/campanhas/$campanhaId'
      fullPath: '/portal/$token/campanhas/$campanhaId'
      preLoaderRoute: typeof PortalTokenCampanhasCampanhaIdRouteImport
      parentRoute: typeof PortalTokenRouteRoute
    }
    '/portal/$token/campanhas/$campanhaId/aprovacoes': {
      id: '/portal/$token/campanhas/$campanhaId/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/portal/$token/campanhas/$campanhaId/aprovacoes'
      preLoaderRoute: typeof PortalTokenCampanhasCampanhaIdAprovacoesRouteImport
      parentRoute: typeof PortalTokenCampanhasCampanhaIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDesignSystemRoute: typeof AuthenticatedDesignSystemRoute
  AuthenticatedDesignSystemFinanceConceptRoute: typeof AuthenticatedDesignSystemFinanceConceptRoute
  AuthenticatedFocoRoute: typeof AuthenticatedFocoRoute
  AuthenticatedPrimeiroAcessoRoute: typeof AuthenticatedPrimeiroAcessoRoute
  AuthenticatedTimeRoute: typeof AuthenticatedTimeRoute
  AuthenticatedProjetoIdRoute: typeof AuthenticatedProjetoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDesignSystemRoute: AuthenticatedDesignSystemRoute,
  AuthenticatedDesignSystemFinanceConceptRoute:
    AuthenticatedDesignSystemFinanceConceptRoute,
  AuthenticatedFocoRoute: AuthenticatedFocoRoute,
  AuthenticatedPrimeiroAcessoRoute: AuthenticatedPrimeiroAcessoRoute,
  AuthenticatedTimeRoute: AuthenticatedTimeRoute,
  AuthenticatedProjetoIdRoute: AuthenticatedProjetoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalTokenCampanhasCampanhaIdRouteChildren {
  PortalTokenCampanhasCampanhaIdAprovacoesRoute: typeof PortalTokenCampanhasCampanhaIdAprovacoesRoute
}

const PortalTokenCampanhasCampanhaIdRouteChildren: PortalTokenCampanhasCampanhaIdRouteChildren =
  {
    PortalTokenCampanhasCampanhaIdAprovacoesRoute:
      PortalTokenCampanhasCampanhaIdAprovacoesRoute,
  }

const PortalTokenCampanhasCampanhaIdRouteWithChildren =
  PortalTokenCampanhasCampanhaIdRoute._addFileChildren(
    PortalTokenCampanhasCampanhaIdRouteChildren,
  )

interface PortalTokenRouteRouteChildren {
  PortalTokenAprovacoesRoute: typeof PortalTokenAprovacoesRoute
  PortalTokenInicioRoute: typeof PortalTokenInicioRoute
  PortalTokenRelatoriosRoute: typeof PortalTokenRelatoriosRoute
  PortalTokenSolicitacoesRoute: typeof PortalTokenSolicitacoesRoute
  PortalTokenIndexRoute: typeof PortalTokenIndexRoute
  PortalTokenCampanhasCampanhaIdRoute: typeof PortalTokenCampanhasCampanhaIdRouteWithChildren
  PortalTokenCampanhasIndexRoute: typeof PortalTokenCampanhasIndexRoute
}

const PortalTokenRouteRouteChildren: PortalTokenRouteRouteChildren = {
  PortalTokenAprovacoesRoute: PortalTokenAprovacoesRoute,
  PortalTokenInicioRoute: PortalTokenInicioRoute,
  PortalTokenRelatoriosRoute: PortalTokenRelatoriosRoute,
  PortalTokenSolicitacoesRoute: PortalTokenSolicitacoesRoute,
  PortalTokenIndexRoute: PortalTokenIndexRoute,
  PortalTokenCampanhasCampanhaIdRoute:
    PortalTokenCampanhasCampanhaIdRouteWithChildren,
  PortalTokenCampanhasIndexRoute: PortalTokenCampanhasIndexRoute,
}

const PortalTokenRouteRouteWithChildren =
  PortalTokenRouteRoute._addFileChildren(PortalTokenRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortalTokenRouteRoute: PortalTokenRouteRouteWithChildren,
  BugsTokenRoute: BugsTokenRoute,
  CalculadoraPropostaTokenRoute: CalculadoraPropostaTokenRoute,
  InscricaoTokenRoute: InscricaoTokenRoute,
  ApiCronEmailFlowsRoute: ApiCronEmailFlowsRoute,
  ApiCronHypitoAlertsRoute: ApiCronHypitoAlertsRoute,
  ApiCronHypitoDailyBriefingRoute: ApiCronHypitoDailyBriefingRoute,
  ApiCronHypitoWeeklyReportRoute: ApiCronHypitoWeeklyReportRoute,
  ApiGoogleOauthCallbackRoute: ApiGoogleOauthCallbackRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
  EmailDescadastroTokenRoute: EmailDescadastroTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
