/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as InscricaoTokenRouteImport } from './routes/inscricao.$token'
import { Route as AuthenticatedTimeRouteImport } from './routes/_authenticated/time'
import { Route as AuthenticatedPrimeiroAcessoRouteImport } from './routes/_authenticated/primeiro-acesso'
import { Route as AuthenticatedBugsRouteImport } from './routes/_authenticated/bugs'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiGoogleOauthCallbackRouteImport } from './routes/api/google/oauth-callback'
import { Route as AuthenticatedProjetoIdRouteImport } from './routes/_authenticated/projeto.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoTokenRoute = InscricaoTokenRouteImport.update({
  id: '/inscricao/$token',
  path: '/inscricao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimeRoute = AuthenticatedTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrimeiroAcessoRoute =
  AuthenticatedPrimeiroAcessoRouteImport.update({
    id: '/primeiro-acesso',
    path: '/primeiro-acesso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBugsRoute = AuthenticatedBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleOauthCallbackRoute = ApiGoogleOauthCallbackRouteImport.update({
  id: '/api/google/oauth-callback',
  path: '/api/google/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetoIdRoute = AuthenticatedProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bugs': typeof AuthenticatedBugsRoute
  '/primeiro-acesso': typeof AuthenticatedPrimeiroAcessoRoute
  '/time': typeof AuthenticatedTimeRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bugs': typeof AuthenticatedBugsRoute
  '/primeiro-acesso': typeof AuthenticatedPrimeiroAcessoRoute
  '/time': typeof AuthenticatedTimeRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/bugs': typeof AuthenticatedBugsRoute
  '/_authenticated/primeiro-acesso': typeof AuthenticatedPrimeiroAcessoRoute
  '/_authenticated/time': typeof AuthenticatedTimeRoute
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_authenticated/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bugs'
    | '/primeiro-acesso'
    | '/time'
    | '/inscricao/$token'
    | '/portal/$token'
    | '/projeto/$id'
    | '/api/google/oauth-callback'
    | '/api/public/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bugs'
    | '/primeiro-acesso'
    | '/time'
    | '/inscricao/$token'
    | '/portal/$token'
    | '/projeto/$id'
    | '/api/google/oauth-callback'
    | '/api/public/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/bugs'
    | '/_authenticated/primeiro-acesso'
    | '/_authenticated/time'
    | '/inscricao/$token'
    | '/portal/$token'
    | '/_authenticated/projeto/$id'
    | '/api/google/oauth-callback'
    | '/api/public/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  InscricaoTokenRoute: typeof InscricaoTokenRoute
  PortalTokenRoute: typeof PortalTokenRoute
  ApiGoogleOauthCallbackRoute: typeof ApiGoogleOauthCallbackRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$token': {
      id: '/inscricao/$token'
      path: '/inscricao/$token'
      fullPath: '/inscricao/$token'
      preLoaderRoute: typeof InscricaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/time': {
      id: '/_authenticated/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthenticatedTimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/primeiro-acesso': {
      id: '/_authenticated/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof AuthenticatedPrimeiroAcessoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bugs': {
      id: '/_authenticated/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof AuthenticatedBugsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/oauth-callback': {
      id: '/api/google/oauth-callback'
      path: '/api/google/oauth-callback'
      fullPath: '/api/google/oauth-callback'
      preLoaderRoute: typeof ApiGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projeto/$id': {
      id: '/_authenticated/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof AuthenticatedProjetoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBugsRoute: typeof AuthenticatedBugsRoute
  AuthenticatedPrimeiroAcessoRoute: typeof AuthenticatedPrimeiroAcessoRoute
  AuthenticatedTimeRoute: typeof AuthenticatedTimeRoute
  AuthenticatedProjetoIdRoute: typeof AuthenticatedProjetoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBugsRoute: AuthenticatedBugsRoute,
  AuthenticatedPrimeiroAcessoRoute: AuthenticatedPrimeiroAcessoRoute,
  AuthenticatedTimeRoute: AuthenticatedTimeRoute,
  AuthenticatedProjetoIdRoute: AuthenticatedProjetoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  InscricaoTokenRoute: InscricaoTokenRoute,
  PortalTokenRoute: PortalTokenRoute,
  ApiGoogleOauthCallbackRoute: ApiGoogleOauthCallbackRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
