-- Tabela de releases da plataforma — fonte única e consultável do
-- histórico de versões (antes vivia só em public/version.json, arquivo
-- estático editado à mão). Habilita: notificação em tempo real via
-- Supabase Realtime (postgres_changes), permissão real de quem publica
-- (is_admin(), já existente), e proteção contra publicar versão
-- duplicada/inferior. public/version.json continua existindo intocado —
-- é usado pelo Portal do Cliente (VersionWatcher.tsx, scope="vc"), que
-- não foi tocado nesta mudança.
create table public.platform_releases (
  id uuid primary key default gen_random_uuid(),
  version text not null unique,
  title text not null,
  summary text,
  -- Lista de mudanças em texto puro — nunca HTML (renderizado sempre
  -- como texto no cliente, nunca dangerouslySetInnerHTML, pra não abrir
  -- brecha de XSS via changelog).
  changes jsonb not null default '[]'::jsonb,
  environment text not null default 'production'
    check (environment in ('production', 'preview', 'development')),
  requires_reload boolean not null default false,
  minimum_supported_version text,
  released_by uuid references auth.users(id) on delete set null,
  released_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index platform_releases_released_at_idx on public.platform_releases (released_at desc);

alter table public.platform_releases enable row level security;

-- Leitura: qualquer usuário autenticado (histórico é informativo, sem
-- dado sensível).
create policy "platform_releases_select_authenticated"
  on public.platform_releases for select
  to authenticated
  using (true);

-- Escrita: só admin — mesma função is_admin() já usada em
-- team.functions.ts/integrations.functions.ts/etc. Sem update/delete: o
-- histórico é um log imomutável (corrigir uma release errada = publicar
-- uma nova, nunca editar o passado).
create policy "platform_releases_insert_admin"
  on public.platform_releases for insert
  to authenticated
  with check (public.is_admin(auth.uid()));

-- Seed do histórico de releases já existente em public/version.json
-- (25 releases, preservadas — nada foi apagado, só migrado pra um lugar
-- que dá pra consultar via API/realtime). released_at é aproximado (o
-- arquivo original não guardava data por release) — usa a data desta
-- migration como base e distancia cada versão anterior em 1 dia, só pra
-- preservar a ORDEM relativa correta no histórico (mais recente primeiro).
insert into public.platform_releases
  (version, title, summary, changes, environment, requires_reload, released_at)
values
  ('1.276.0', 'HYPITO', 'Hypito ganha cards visuais nas respostas do Chat — ainda em desenvolvimento.', '[{"title": "Respostas em cards, não mais em texto cru", "description": "Tarefa criada, resumo de campanha/projeto, agenda agrupada por dia e listas de tarefas agora aparecem em cards visuais com botões reais e links diretos pro item certo — sem rota interna aparecendo na conversa."}, {"title": "Confirmação e escolha entre opções mais claras", "description": "Criar uma tarefa mostra um card de confirmação antes de gravar qualquer coisa; quando há mais de uma campanha ou pessoa parecida, o Hypito oferece opções clicáveis em vez de pedir pra você repetir a pergunta."}, {"title": "Ainda em desenvolvimento", "description": "O Hypito continua sem IA generativa (é baseado em regras), então a conversa ainda pode soar menos natural que uma conversa humana e nem toda frase é reconhecida da primeira vez. Estamos evoluindo isso aos poucos — se algo não for entendido, tente reformular de um jeito mais direto."}]'::jsonb, 'production', false, '2026-09-16T12:00:00'::timestamptz),
  ('1.275.0', 'HYPITO', 'Lança o Hypito — assistente operacional com conversa no Chat, resumo diário, relatório semanal e alertas preventivos.', '[{"title": "Converse com o Hypito no Chat", "description": "Pergunte sobre suas tarefas, agenda, projetos e campanhas em linguagem natural. As respostas sempre respeitam suas permissões e trazem links diretos pros itens citados."}, {"title": "Criação assistida de tarefas e lembretes", "description": "Peça pro Hypito criar uma tarefa ou lembrete — ele monta um rascunho e só grava depois da sua confirmação explícita."}, {"title": "Resumo diário e relatório semanal", "description": "Todo dia útil de manhã, um resumo pessoal na DM com o Hypito. Toda sexta às 17h, um relatório semanal no canal Geral com destaques, riscos e um insight individual por pessoa."}, {"title": "Alertas preventivos", "description": "O Hypito avisa sobre tarefas atrasadas, prioridades sem prazo e reuniões sem confirmação antes que virem problema — sem repetir o mesmo aviso sem necessidade."}]'::jsonb, 'production', false, '2026-09-15T12:00:00'::timestamptz),
  ('1.274.0', 'INÍCIO', 'Home repaginada: as seções abaixo do clima ganham o acabamento premium do design system.', '[{"title": "Meu trabalho, Agenda, Mural, Comentários e Lista pessoal", "description": "Mesmos cantos arredondados, superfícies, tipografia e estados vazios compactos do restante da plataforma — a Home inteira agora parece um único produto."}]'::jsonb, 'production', false, '2026-09-14T12:00:00'::timestamptz),
  ('1.273.0', 'INÍCIO', 'Cabeçalho do Início reformulado (clima + indicadores num só bloco); @menção e exclusão de comentário no Mural; corrige spam de chamada encerrada.', '[{"title": "Clima e indicadores no mesmo bloco", "description": "Hoje, Amanhã, Próximos 7 dias e Atrasadas saem da fileira de cards separada e passam a viver dentro do próprio cabeçalho, junto com a saudação e o clima. Composição sempre coerente, para qualquer condição do tempo."}, {"title": "Chuva do cabeçalho mais visível", "description": "O efeito visual de chuva ficou mais perceptível, inclusive no tema claro, e reage instantaneamente à troca de tema sem reiniciar a animação."}, {"title": "@menção nos comentários de artigo", "description": "Digite @ num comentário de artigo interno pra marcar alguém do time, igual já funciona nas tarefas."}, {"title": "Excluir comentário", "description": "Comentários de artigo agora podem ser excluídos."}, {"title": "Aviso de chamada encerrada não duplica mais", "description": "Com mais de uma aba aberta, o encerramento de uma chamada podia gerar várias mensagens idênticas de \"Chamada encerrada\" no chat. Agora só uma é enviada."}]'::jsonb, 'production', false, '2026-09-13T12:00:00'::timestamptz),
  ('1.272.0', 'MODO FOCO', 'Novo Modo Foco (Pomodoro) e clima ao vivo no cabeçalho do Início; Projetos com novo visual.', '[{"title": "Nova experiência imersiva de foco", "description": "Acesse pelo botão no cabeçalho ou por \"Iniciar foco\" em qualquer tarefa. Cronômetro preciso, ciclos de foco/pausa, música Lo-fi/clássica/chuva geradas ao vivo (sem áudio externo) e chuva visual sutil no fundo."}, {"title": "Suas tarefas reais, sem sair do foco", "description": "Escolha entre suas tarefas de Projetos, Campanhas e Marketing direto no painel do Modo Foco, marque como concluída ou registre o tempo trabalhado sem trocar de tela."}, {"title": "Temperatura e condição do tempo na saudação", "description": "O cabeçalho do Início agora mostra a temperatura e a condição do tempo atual, com uma ambientação visual discreta (chuva, névoa ou céu limpo) — pode ser desativado em \"Gerenciar cards\"."}, {"title": "Cabeçalho azul com resumo do projeto", "description": "Cada projeto ganhou um cabeçalho compacto com progresso, fase atual, responsável e próxima entrega, além de Roadmap e Bugs & sugestões com o visual atualizado."}]'::jsonb, 'production', false, '2026-09-12T12:00:00'::timestamptz),
  ('1.271.0', 'PLATAFORMA', 'Migração visual para o novo design system em toda a plataforma, com o Chat ganhando telas separadas para desktop e mobile.', '[{"title": "Visual consistente em toda a plataforma", "description": "Início, Projetos, Campanhas, Banco de influenciadores, Financeiro, Comercial, Metas e Time passaram a usar os mesmos tokens de tipografia, cor e espaçamento — botões de ação em azul, verde e vermelho reservados só para status."}, {"title": "Aviso de nova versão com o visual atualizado", "description": "O próprio aviso de \"Nova versão disponível\" e a tela \"O que há de novo\" foram atualizados para o novo design system."}, {"title": "Desktop aproveita melhor o espaço", "description": "O histórico deixou de ficar espremido numa coluna estreita — agora usa a largura disponível, com mensagens próprias e recebidas claramente diferenciadas lado a lado."}, {"title": "Mobile com teclado e rolagem corrigidos", "description": "Navegação em duas telas (lista e conversa), campo de mensagem sempre visível acima do teclado e rolagem sem saltos, preservados integralmente na correção do desktop."}]'::jsonb, 'production', false, '2026-09-11T12:00:00'::timestamptz),
  ('1.270.0', 'PLATAFORMA', 'Correção de responsividade mobile em toda a plataforma — a causa raiz de páginas ficarem arrastáveis na horizontal foi corrigida no componente de abas compartilhado.', '[{"title": "Páginas não ficam mais arrastáveis de lado", "description": "Abas com várias opções (Financeiro, Reuniões e outras) faziam a tela inteira rolar na horizontal em celulares. Corrigido na raiz, no componente de abas compartilhado por todo o app."}, {"title": "Menu mobile com Escape e foco correto", "description": "O menu lateral no celular agora fecha com Escape, leva o foco pro primeiro item ao abrir e devolve pro botão de abrir ao fechar."}, {"title": "Kanban e Pipeline com modo mobile", "description": "Em telas de celular, mostram só a etapa/coluna ativa (sem rolagem horizontal), com chips para trocar — arrastar card continua funcionando normalmente no desktop."}, {"title": "Diálogos e filtros ajustados", "description": "Vários diálogos do Financeiro e o \"+Filtros\" ganharam o mesmo comportamento de tela cheia/sem cortes já usado nos outros diálogos grandes do app."}]'::jsonb, 'production', false, '2026-09-10T12:00:00'::timestamptz),
  ('1.269.0', 'FINANCEIRO', 'Redesign completo do Financeiro: central financeira com 6 abas, definições e totais rotulados e reconciliados, faixas de vencimento/atraso, saldo inicial configurável, cobrança e recebimento parcial.', '[{"title": "6 abas: Visão geral, Movimentações, A receber, A pagar, Campanhas, Relatórios", "description": "Campanhas e Relatórios são novas — resultado por campanha (contratado/realizado) e relatórios reais (inadimplência, aging, prazo médio, evolução mensal e mais), sem métrica inventada."}, {"title": "Totais rotulados e reconciliados", "description": "O total \"a pagar\" da Visão geral e o da aba A pagar podiam divergir sem explicação — eram escopos diferentes (mês vs. toda a carteira). Agora cada tela rotula o escopo que está mostrando, e os dois batem."}, {"title": "Saldo atual nunca é inventado", "description": "Sem um saldo inicial configurado, mostra \"Saldo não configurado\" com uma ação — nunca R$ 0,00 ou um número estimado. Saldo projetado agora tem horizonte explícito (fim do mês/30/90 dias)."}, {"title": "Faixas de vencimento e atraso", "description": "Vencido/Vence hoje/Próximos 7 dias/8 a 30 dias/Acima de 30 dias (mutuamente exclusivas) em A receber e A pagar, mais aging de recebíveis no novo relatório."}, {"title": "Recebimento/pagamento parcial e cobrança", "description": "Marcar como pago/recebido aceita valor parcial, mantendo o saldo restante visível. Nova ação \"Registrar cobrança\" em A receber, com histórico."}, {"title": "Movimentações: exportar, selecionar em lote, importar sem duplicar", "description": "Exportação CSV, seleção múltipla com exclusão em lote, paginação, e a importação por texto colado agora ignora linhas já existentes."}]'::jsonb, 'production', false, '2026-09-09T12:00:00'::timestamptz),
  ('1.268.1', 'FINANCEIRO', 'Corrige comprovante de pagamento desaparecendo ao marcar um lançamento do Financeiro como pago.', '[{"title": "Comprovante não some mais", "description": "O arquivo já subia normalmente, mas a referência a ele nunca era gravada no lançamento — agora fica salva, tanto em lançamentos manuais quanto nos gerados automaticamente por campanha, influenciador e salário."}]'::jsonb, 'production', false, '2026-09-08T12:00:00'::timestamptz),
  ('1.268.0', 'COMERCIAL', 'Visão geral do Comercial fica mais direta: só 4 indicadores e 2 blocos que ajudam a decidir.', '[{"title": "Só o que ajuda a decidir", "description": "Removidos Forecast, \"Oportunidades abertas\", Pipeline por responsável, \"Em risco\" e \"Mais avançadas no funil\" — ficam só Pipeline total, Ganho no período, Sem próxima ação e Paradas, cada um clicável direto pro Pipeline já filtrado."}, {"title": "Prioridades comerciais", "description": "Uma lista só (sem repetir a mesma oportunidade) priorizando quem tem ação vencida, depois sem próxima ação, depois parada, depois reunião hoje/próximos dias."}, {"title": "Pipeline total corrigido", "description": "O indicador estava somando até negócios já ganhos ou perdidos — agora reflete só o que está de fato em aberto."}]'::jsonb, 'production', false, '2026-09-07T12:00:00'::timestamptz),
  ('1.267.1', 'COMERCIAL', 'Ajustes no Comercial: menos abas, botão da calculadora externa de volta, Visão geral redesenhada.', '[{"title": "Menos abas", "description": "Removidas Atividades e Relatórios — a navegação fica só com Visão geral e Pipeline."}, {"title": "Calculadora externa de volta", "description": "O botão na aba Proposta tinha ficado escondido até a proposta já existir — volta a aparecer sempre."}, {"title": "Visão geral com mais destaque visual", "description": "Estatísticas em cartões no topo e pipeline por etapa/responsável como barras proporcionais ao valor real."}]'::jsonb, 'production', false, '2026-09-06T12:00:00'::timestamptz),
  ('1.267.0', 'COMERCIAL', 'Comercial ganha um redesign completo: virou uma central de vendas, não só um Kanban.', '[{"title": "Pipeline em tela cheia", "description": "Kanban usa toda a largura da tela, com cabeçalho de coluna fixo, rolagem própria e feedback visual ao arrastar um card."}, {"title": "Cards mais claros", "description": "Cada card mostra o essencial (empresa, contato, valor, responsável, próxima ação) com um único indicador de risco, em vez de vários badges disputando atenção."}, {"title": "Ficha da oportunidade mais compacta", "description": "O painel lateral encolheu e ganhou 3 abas (Visão geral, Proposta, Histórico), sem repetir informação do cabeçalho."}, {"title": "Filtros, indicadores e 3 novas visões", "description": "Nova barra de filtros com chips, indicadores no topo (pipeline, ganho no período, paradas, ações vencidas) e as visões Visão geral/Atividades/Relatórios — sempre mostrando \"—\" quando o dado não existe, nunca um número inventado."}]'::jsonb, 'production', false, '2026-09-05T12:00:00'::timestamptz),
  ('1.266.1', 'COMERCIAL', 'Corrige item da calculadora de proposta externa sobrepondo o preço em telas mais estreitas.', '[{"title": "Preço não sobrepõe mais os seletores", "description": "Em telas mais estreitas, o valor do item podia aparecer por cima do campo de quantidade — os seletores de Porte e Formato agora encolhem corretamente."}]'::jsonb, 'production', false, '2026-09-04T12:00:00'::timestamptz),
  ('1.266.0', 'TIME', 'Corrige o Score Operacional dando pontuação alta a quem não tem dados, e adiciona salvaguardas contra scores incoerentes.', '[{"title": "\"Sem dados\" em vez de pontuação de fábrica", "description": "Quem não tem nenhuma tarefa concluída ou atrasada no período agora aparece como \"Sem dados\" (nunca um número) — antes recebia até 35 pontos automaticamente por falta de dado."}, {"title": "\"Provisório\" com amostra pequena", "description": "Com menos de 5 tarefas no período, o Score é calculado mas fica marcado \"Provisório\", sem a classificação Excelente/Bom/Atenção/Crítico até ter dado suficiente."}, {"title": "Salvaguardas contra Score incoerente", "description": "Taxa de entrega baixa, tarefa de prioridade alta muito atrasada, acúmulo de tarefas atrasadas ou zero pontos em Entrega agora sempre limitam o Score final — nenhuma nota boa nas outras dimensões consegue mascarar um problema grave de entrega."}, {"title": "Compromissos vira \"Não aplicável\" sem reunião", "description": "Sem reunião esperada no período, essa dimensão não soma nem penaliza — o peso é redistribuído entre Entrega e Previsibilidade, em vez de contar como zero."}]'::jsonb, 'production', false, '2026-09-03T12:00:00'::timestamptz),
  ('1.265.0', 'COMERCIAL', 'Nova calculadora de proposta externa no Comercial — link à parte pra abrir durante calls com o cliente.', '[{"title": "Link da calculadora pro cliente", "description": "Cada lead ganha um botão \"Calculadora externa\" na aba Proposta — gera um link à parte (mesmo padrão do \"Link do cliente\") pra abrir durante a call: monte o pacote por porte × formato × quantidade e veja o investimento total ao vivo, sem mostrar custo interno nem margem da agência."}, {"title": "Salvar a simulação", "description": "Um botão \"Salvar esta simulação\" na própria calculadora grava o pacote mostrado ao cliente de volta no lead, pra não precisar copiar os números manualmente depois da call."}]'::jsonb, 'production', false, '2026-09-02T12:00:00'::timestamptz),
  ('1.264.3', 'TAREFAS', 'Corrige o painel de Activity/Comentários da tarefa não rolando de verdade.', '[{"title": "Comentários rolam de novo", "description": "O painel de Activity/Comentários ficava do tamanho do próprio conteúdo em vez de rolar dentro do espaço disponível — corrigido."}]'::jsonb, 'production', false, '2026-09-01T12:00:00'::timestamptz),
  ('1.264.2', 'TAREFAS', 'Corrige timeout ao salvar tarefas com anexos — anexos agora sobem pro Storage em vez de inflar a tarefa.', '[{"title": "Sem mais timeout ao salvar", "description": "Anexos de tarefa deixaram de ser embutidos como base64 no registro da tarefa (o que podia inflar uma tarefa com subtarefas anexadas pra vários MB e travar qualquer save) — agora sobem pra um armazenamento próprio, como já acontecia no Chat."}]'::jsonb, 'production', false, '2026-08-31T12:00:00'::timestamptz),
  ('1.264.1', 'TAREFAS', 'Corrige o diálogo de tarefa travando o scroll antes do fim, escondendo subtarefas e anexos.', '[{"title": "Scroll até o fim de novo", "description": "O diálogo de tarefa parava de rolar antes de mostrar subtarefas e anexos — corrigido, agora rola até o fim em qualquer tarefa."}]'::jsonb, 'production', false, '2026-08-30T12:00:00'::timestamptz),
  ('1.264.0', 'TAREFAS', 'Novo menu "⋯" na tarefa: mover pra outro projeto/campanha/Marketing, duplicar, arquivar e mais.', '[{"title": "Mover tarefa", "description": "Transfira uma tarefa pra outro projeto, campanha ou pro Kanban do Marketing — comentários, anexos, subtarefas e dependências continuam funcionando depois do move."}, {"title": "Duplicar, Arquivar e atalhos", "description": "Duplicar cria uma cópia limpa (sem histórico da original); Arquivar muda o status com um clique; Relacionamentos e Histórico levam direto às seções já existentes na tarefa."}]'::jsonb, 'production', false, '2026-08-29T12:00:00'::timestamptz),
  ('1.263.4', 'PROJETOS', 'Visão geral do Roadmap mais enxuta: menos indicadores, período por fase.', '[{"title": "Indicadores removidos", "description": "Some \"Tarefas atrasadas\", \"Tarefas sem fase\" e \"Responsáveis\" da Visão geral do Roadmap."}, {"title": "Período da fase, não do projeto", "description": "O card de período agora mostra as datas da fase atual, em vez do intervalo entre todas as fases do projeto."}]'::jsonb, 'production', false, '2026-08-28T12:00:00'::timestamptz),
  ('1.263.3', 'PROJETOS', 'Remove Marcos do Roadmap — as fases já cobrem esse papel.', '[{"title": "Marcos removidos", "description": "O Roadmap não tem mais a seção de Marcos (formulário, linha do tempo e o indicador \"Próximo marco\") — as fases já servem esse propósito. Nenhuma tarefa foi apagada."}]'::jsonb, 'production', false, '2026-08-27T12:00:00'::timestamptz),
  ('1.263.2', 'PROJETOS', 'Reverte a fusão do Kanban dentro do Roadmap — cada um volta a ser sua própria aba.', '[{"title": "Kanban é aba própria de novo", "description": "\"Kanban\" e \"Roadmap\" voltam a ser abas separadas na página do projeto, como eram antes. O Roadmap volta a ser uma tela única, sem sub-abas."}, {"title": "Fases continuam funcionando igual", "description": "Nenhuma mudança no modelo de dados — fases, vínculo de tarefas, filtro/agrupamento por fase no Kanban e o menu \"Mover para fase\" continuam exatamente como antes."}]'::jsonb, 'production', false, '2026-08-26T12:00:00'::timestamptz),
  ('1.263.1', 'PROJETOS', 'Roadmap: Kanban agora agrupa por fase, e mover tarefa entre fases ganhou um menu (além do arrastar).', '[{"title": "Kanban agrupado por fase", "description": "Novo toggle \"Agrupar por: Status | Fase\" no Kanban do projeto — agrupando por fase, cada coluna vira uma fase (+ \"Sem fase\") e arrastar entre colunas move a tarefa de fase."}, {"title": "Mover tarefa por menu", "description": "Cada tarefa dentro de uma fase (ou em \"Tarefas sem fase\") ganhou um menu \"Mover para fase\" — funciona em qualquer dispositivo, sem depender de arrastar."}]'::jsonb, 'production', false, '2026-08-25T12:00:00'::timestamptz),
  ('1.263.0', 'PROJETOS', 'Roadmap dos projetos ganha fases reais, integradas ao Kanban.', '[{"title": "Fases do roadmap", "description": "Cada projeto pode ter fases (nome, período, responsável, cor, status) — crie, edite, reordene e exclua sem nunca apagar as tarefas vinculadas (voltam para \"Sem fase\")."}, {"title": "Tarefas ligadas às fases", "description": "Vincule tarefas existentes (uma a uma ou em massa) ou crie uma tarefa já dentro da fase — ela aparece na fase e no Kanban ao mesmo tempo, com um filtro por fase novo no Kanban."}, {"title": "Progresso e status automáticos", "description": "Cada fase mostra progresso real (concluídas/total) e um status que combina o que foi definido manualmente com atraso/risco calculado pelas datas e tarefas pendentes."}, {"title": "Nova estrutura em 3 abas", "description": "Visão geral, Roadmap e Tarefas substituem o Kanban solto que ficava sempre visível embaixo da linha do tempo."}]'::jsonb, 'production', false, '2026-08-24T12:00:00'::timestamptz),
  ('1.262.2', 'METAS', 'Corrige indicador de Metas "Reduzir" com meta zero/negativa mostrando Saudável mesmo estando bem pior que a meta.', '[{"title": "Cálculo corrigido", "description": "Indicadores com direção \"Reduzir\" e meta ≤ 0 (ex. \"Limite 0 Pendências\") não mostram mais 100%/Saudável quando o valor real está pior e indo na direção errada."}]'::jsonb, 'production', false, '2026-08-23T12:00:00'::timestamptz)
on conflict (version) do nothing;
