// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.17"
  }
  public: {
    Tables: {
      aeo_prompts: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      aeo_respostas: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      banco_influenciadores: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      blog_comments: {
        Row: {
          author_kind: string
          author_label: string
          body: string
          created_at: string
          id: string
          post_id: string
        }
        Insert: {
          author_kind: string
          author_label: string
          body: string
          created_at?: string
          id?: string
          post_id: string
        }
        Update: {
          author_kind?: string
          author_label?: string
          body?: string
          created_at?: string
          id?: string
          post_id?: string
        }
        Relationships: []
      }
      blog_likes: {
        Row: {
          created_at: string
          id: string
          liker_key: string
          liker_label: string
          post_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          liker_key: string
          liker_label: string
          post_id: string
        }
        Update: {
          created_at?: string
          id?: string
          liker_key?: string
          liker_label?: string
          post_id?: string
        }
        Relationships: []
      }
      bug_reports: {
        Row: {
          client_label: string | null
          created_at: string
          description: string
          id: string
          kind: string
          page_context: string | null
          reporter_id: string | null
          reporter_name: string
          resolved: boolean
          resolved_at: string | null
          scope: string | null
          screenshot_path: string | null
          source: string
        }
        Insert: {
          client_label?: string | null
          created_at?: string
          description: string
          id?: string
          kind?: string
          page_context?: string | null
          reporter_id?: string | null
          reporter_name?: string
          resolved?: boolean
          resolved_at?: string | null
          scope?: string | null
          screenshot_path?: string | null
          source?: string
        }
        Update: {
          client_label?: string | null
          created_at?: string
          description?: string
          id?: string
          kind?: string
          page_context?: string | null
          reporter_id?: string | null
          reporter_name?: string
          resolved?: boolean
          resolved_at?: string | null
          scope?: string | null
          screenshot_path?: string | null
          source?: string
        }
        Relationships: []
      }
      campanha_cronograma: {
        Row: {
          campanha_id: string
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          campanha_id: string
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          campanha_id?: string
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      campanha_documentos: {
        Row: {
          campanha_id: string
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          campanha_id: string
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          campanha_id?: string
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      campanha_influenciadores: {
        Row: {
          campanha_id: string
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          campanha_id: string
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          campanha_id?: string
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      campanha_tarefas: {
        Row: {
          campanha_id: string
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          campanha_id: string
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          campanha_id?: string
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      chat_channels: {
        Row: {
          allowed_member_ids: string[]
          created_at: string
          id: string
          is_private: boolean
          name: string
          photo: string | null
          sort_order: number
          updated_at: string
        }
        Insert: {
          allowed_member_ids?: string[]
          created_at?: string
          id?: string
          is_private?: boolean
          name: string
          photo?: string | null
          sort_order?: number
          updated_at?: string
        }
        Update: {
          allowed_member_ids?: string[]
          created_at?: string
          id?: string
          is_private?: boolean
          name?: string
          photo?: string | null
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      chat_deliveries: {
        Row: {
          convo_id: string
          last_delivered_at: string
          user_id: string
        }
        Insert: {
          convo_id: string
          last_delivered_at?: string
          user_id: string
        }
        Update: {
          convo_id?: string
          last_delivered_at?: string
          user_id?: string
        }
        Relationships: []
      }
      chat_messages: {
        Row: {
          attachments: Json
          author_id: string | null
          author_name: string
          author_photo: string | null
          convo_id: string
          created_at: string
          edited_at: string | null
          id: string
          mentions: Json
          reactions: Json
          reply_to_id: string | null
          text: string
        }
        Insert: {
          attachments?: Json
          author_id?: string | null
          author_name: string
          author_photo?: string | null
          convo_id: string
          created_at?: string
          edited_at?: string | null
          id?: string
          mentions?: Json
          reactions?: Json
          reply_to_id?: string | null
          text: string
        }
        Update: {
          attachments?: Json
          author_id?: string | null
          author_name?: string
          author_photo?: string | null
          convo_id?: string
          created_at?: string
          edited_at?: string | null
          id?: string
          mentions?: Json
          reactions?: Json
          reply_to_id?: string | null
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "chat_messages_reply_to_id_fkey"
            columns: ["reply_to_id"]
            isOneToOne: false
            referencedRelation: "chat_messages"
            referencedColumns: ["id"]
          },
        ]
      }
      chat_reads: {
        Row: {
          convo_id: string
          last_read_at: string
          user_id: string
        }
        Insert: {
          convo_id: string
          last_read_at?: string
          user_id: string
        }
        Update: {
          convo_id?: string
          last_read_at?: string
          user_id?: string
        }
        Relationships: []
      }
      chat_status: {
        Row: {
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      clientes: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      email_flow_enrollments: {
        Row: {
          cancelled_reason: string | null
          current_step_index: number
          enrolled_at: string
          entity_id: string
          entity_type: string
          flow_id: string
          id: string
          next_run_at: string | null
          status: string
          to_email: string
          to_name: string | null
          updated_at: string
        }
        Insert: {
          cancelled_reason?: string | null
          current_step_index?: number
          enrolled_at?: string
          entity_id: string
          entity_type: string
          flow_id: string
          id?: string
          next_run_at?: string | null
          status?: string
          to_email: string
          to_name?: string | null
          updated_at?: string
        }
        Update: {
          cancelled_reason?: string | null
          current_step_index?: number
          enrolled_at?: string
          entity_id?: string
          entity_type?: string
          flow_id?: string
          id?: string
          next_run_at?: string | null
          status?: string
          to_email?: string
          to_name?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "email_flow_enrollments_flow_id_fkey"
            columns: ["flow_id"]
            isOneToOne: false
            referencedRelation: "email_flows"
            referencedColumns: ["id"]
          },
        ]
      }
      email_flows: {
        Row: {
          active: boolean
          audience: string
          created_at: string
          created_by: string | null
          id: string
          name: string
          steps: Json
          trigger_config: Json
          trigger_type: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          audience: string
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          steps?: Json
          trigger_config?: Json
          trigger_type: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          audience?: string
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          steps?: Json
          trigger_config?: Json
          trigger_type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "email_flows_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      email_provider_settings: {
        Row: {
          api_key: string | null
          domain_verified_at: string | null
          from_email: string | null
          from_name: string | null
          id: boolean
          provider: string
          reply_to: string | null
          sending_domain: string | null
          updated_at: string
        }
        Insert: {
          api_key?: string | null
          domain_verified_at?: string | null
          from_email?: string | null
          from_name?: string | null
          id?: boolean
          provider?: string
          reply_to?: string | null
          sending_domain?: string | null
          updated_at?: string
        }
        Update: {
          api_key?: string | null
          domain_verified_at?: string | null
          from_email?: string | null
          from_name?: string | null
          id?: boolean
          provider?: string
          reply_to?: string | null
          sending_domain?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      email_sends: {
        Row: {
          clicked_at: string | null
          created_at: string
          enrollment_id: string | null
          error: string | null
          id: string
          opened_at: string | null
          provider_message_id: string | null
          sent_at: string | null
          status: string
          subject: string
          template_id: string | null
          to_email: string
          unsubscribe_token: string
        }
        Insert: {
          clicked_at?: string | null
          created_at?: string
          enrollment_id?: string | null
          error?: string | null
          id?: string
          opened_at?: string | null
          provider_message_id?: string | null
          sent_at?: string | null
          status?: string
          subject: string
          template_id?: string | null
          to_email: string
          unsubscribe_token?: string
        }
        Update: {
          clicked_at?: string | null
          created_at?: string
          enrollment_id?: string | null
          error?: string | null
          id?: string
          opened_at?: string | null
          provider_message_id?: string | null
          sent_at?: string | null
          status?: string
          subject?: string
          template_id?: string | null
          to_email?: string
          unsubscribe_token?: string
        }
        Relationships: [
          {
            foreignKeyName: "email_sends_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "email_flow_enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "email_sends_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "email_templates"
            referencedColumns: ["id"]
          },
        ]
      }
      email_templates: {
        Row: {
          audience: string
          body_html: string
          created_at: string
          created_by: string | null
          id: string
          name: string
          subject: string
          updated_at: string
        }
        Insert: {
          audience: string
          body_html?: string
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          subject: string
          updated_at?: string
        }
        Update: {
          audience?: string
          body_html?: string
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          subject?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "email_templates_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      email_unsubscribes: {
        Row: {
          email: string
          reason: string | null
          unsubscribed_at: string
        }
        Insert: {
          email: string
          reason?: string | null
          unsubscribed_at?: string
        }
        Update: {
          email?: string
          reason?: string | null
          unsubscribed_at?: string
        }
        Relationships: []
      }
      financeiro_lancamentos: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      google_calendar_connections: {
        Row: {
          access_token: string
          connected_at: string
          google_email: string | null
          refresh_token: string
          token_expiry: string
          updated_at: string
          user_id: string
        }
        Insert: {
          access_token: string
          connected_at?: string
          google_email?: string | null
          refresh_token: string
          token_expiry: string
          updated_at?: string
          user_id: string
        }
        Update: {
          access_token?: string
          connected_at?: string
          google_email?: string | null
          refresh_token?: string
          token_expiry?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      google_oauth_states: {
        Row: {
          created_at: string
          purpose: string
          token: string
          user_id: string
        }
        Insert: {
          created_at?: string
          purpose?: string
          token: string
          user_id: string
        }
        Update: {
          created_at?: string
          purpose?: string
          token?: string
          user_id?: string
        }
        Relationships: []
      }
      leads: {
        Row: {
          activities: Json
          company: string | null
          contact: string | null
          created_at: string
          email: string | null
          extra: Json
          id: string
          name: string
          next_meeting: string | null
          notes: string | null
          phone: string | null
          responsible: string | null
          source: string | null
          source_form: string | null
          stage: string
          tags: Json
          updated_at: string
          value: number
        }
        Insert: {
          activities?: Json
          company?: string | null
          contact?: string | null
          created_at?: string
          email?: string | null
          extra?: Json
          id?: string
          name: string
          next_meeting?: string | null
          notes?: string | null
          phone?: string | null
          responsible?: string | null
          source?: string | null
          source_form?: string | null
          stage?: string
          tags?: Json
          updated_at?: string
          value?: number
        }
        Update: {
          activities?: Json
          company?: string | null
          contact?: string | null
          created_at?: string
          email?: string | null
          extra?: Json
          id?: string
          name?: string
          next_meeting?: string | null
          notes?: string | null
          phone?: string | null
          responsible?: string | null
          source?: string | null
          source_form?: string | null
          stage?: string
          tags?: Json
          updated_at?: string
          value?: number
        }
        Relationships: []
      }
      marketing_standalone_tasks: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      marketing_tasks: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      metas: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      outgoing_webhooks: {
        Row: {
          active: boolean
          created_at: string
          created_by: string | null
          events: Json
          id: string
          url: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          events?: Json
          id?: string
          url: string
        }
        Update: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          events?: Json
          id?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "outgoing_webhooks_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      password_reset_requests: {
        Row: {
          created_at: string
          email: string
          id: string
          resolved: boolean
          resolved_at: string | null
          resolved_by: string | null
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          resolved?: boolean
          resolved_at?: string | null
          resolved_by?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          resolved?: boolean
          resolved_at?: string | null
          resolved_by?: string | null
        }
        Relationships: []
      }
      pricing_settings: {
        Row: {
          bonificacao_pct: number
          comissao_pct: number
          custos_tier: Json
          id: boolean
          imposto_pct: number
          margem_pct: number
          updated_at: string
        }
        Insert: {
          bonificacao_pct?: number
          comissao_pct?: number
          custos_tier?: Json
          id?: boolean
          imposto_pct?: number
          margem_pct?: number
          updated_at?: string
        }
        Update: {
          bonificacao_pct?: number
          comissao_pct?: number
          custos_tier?: Json
          id?: boolean
          imposto_pct?: number
          margem_pct?: number
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          birthday: string | null
          created_at: string
          email: string
          full_name: string | null
          id: string
          last_day_started_at: string | null
          must_change_password: boolean
          permissions: Json
          phone: string | null
          photo_url: string | null
          role_label: string | null
          salary: string | null
          start_times: Json
          time_view: Json
          updated_at: string
        }
        Insert: {
          birthday?: string | null
          created_at?: string
          email: string
          full_name?: string | null
          id: string
          last_day_started_at?: string | null
          must_change_password?: boolean
          permissions?: Json
          phone?: string | null
          photo_url?: string | null
          role_label?: string | null
          salary?: string | null
          start_times?: Json
          time_view?: Json
          updated_at?: string
        }
        Update: {
          birthday?: string | null
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          last_day_started_at?: string | null
          must_change_password?: boolean
          permissions?: Json
          phone?: string | null
          photo_url?: string | null
          role_label?: string | null
          salary?: string | null
          start_times?: Json
          time_view?: Json
          updated_at?: string
        }
        Relationships: []
      }
      projeto_influenciadores: {
        Row: {
          created_at: string
          data: Json
          id: string
          projeto_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          projeto_id: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          projeto_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      projeto_tarefas: {
        Row: {
          created_at: string
          data: Json
          id: string
          projeto_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          projeto_id: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          projeto_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      projetos: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          p256dh: string
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          p256dh: string
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          p256dh?: string
          user_id?: string
        }
        Relationships: []
      }
      reunioes: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      reunioes_disponibilidade: {
        Row: {
          created_at: string
          data: Json
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          data?: Json
          id: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      shared_calendar_connection: {
        Row: {
          access_token: string
          connected_at: string
          google_email: string | null
          id: boolean
          refresh_token: string
          token_expiry: string
          updated_at: string
        }
        Insert: {
          access_token: string
          connected_at?: string
          google_email?: string | null
          id?: boolean
          refresh_token: string
          token_expiry: string
          updated_at?: string
        }
        Update: {
          access_token?: string
          connected_at?: string
          google_email?: string | null
          id?: boolean
          refresh_token?: string
          token_expiry?: string
          updated_at?: string
        }
        Relationships: []
      }
      shared_state: {
        Row: {
          data: Json
          key: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          data: Json
          key: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          data?: Json
          key?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      sudoku_daily_results: {
        Row: {
          created_at: string
          date_key: string
          id: string
          time_ms: number
          user_id: string
        }
        Insert: {
          created_at?: string
          date_key: string
          id?: string
          time_ms: number
          user_id: string
        }
        Update: {
          created_at?: string
          date_key?: string
          id?: string
          time_ms?: number
          user_id?: string
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          created_at: string
          id: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: []
      }
      vault_secret: {
        Row: {
          created_at: string
          id: boolean
          key_b64: string
        }
        Insert: {
          created_at?: string
          id?: boolean
          key_b64: string
        }
        Update: {
          created_at?: string
          id?: boolean
          key_b64?: string
        }
        Relationships: []
      }
      vault_totp_attempts: {
        Row: {
          failed_count: number
          locked_until: string | null
          user_id: string
        }
        Insert: {
          failed_count?: number
          locked_until?: string | null
          user_id: string
        }
        Update: {
          failed_count?: number
          locked_until?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vault_totp_attempts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      vault_totp_secrets: {
        Row: {
          admin_id: string
          created_at: string
          secret: string
        }
        Insert: {
          admin_id: string
          created_at?: string
          secret: string
        }
        Update: {
          admin_id?: string
          created_at?: string
          secret?: string
        }
        Relationships: [
          {
            foreignKeyName: "vault_totp_secrets_admin_id_fkey"
            columns: ["admin_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      webhook_settings: {
        Row: {
          key: string
          secret: string
          updated_at: string
        }
        Insert: {
          key: string
          secret: string
          updated_at?: string
        }
        Update: {
          key?: string
          secret?: string
          updated_at?: string
        }
        Relationships: []
      }
      workspace_settings: {
        Row: {
          id: boolean
          logo: string | null
          nome: string
          updated_at: string
        }
        Insert: {
          id?: boolean
          logo?: string | null
          nome?: string
          updated_at?: string
        }
        Update: {
          id?: boolean
          logo?: string | null
          nome?: string
          updated_at?: string
        }
        Relationships: []
      }
      zip_daily_results: {
        Row: {
          created_at: string
          date_key: string
          id: string
          moves: number
          time_ms: number
          user_id: string
        }
        Insert: {
          created_at?: string
          date_key: string
          id?: string
          moves: number
          time_ms: number
          user_id: string
        }
        Update: {
          created_at?: string
          date_key?: string
          id?: string
          moves?: number
          time_ms?: number
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      enroll_email_flow: {
        Args: {
          p_email: string
          p_entity_id: string
          p_entity_type: string
          p_flow_id: string
          p_name: string
        }
        Returns: undefined
      }
      has_permission: {
        Args: { _permission: string; _user_id: string }
        Returns: boolean
      }
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"]
          _user_id: string
        }
        Returns: boolean
      }
      is_admin: { Args: { _user_id: string }; Returns: boolean }
      run_scheduled_email_triggers: { Args: never; Returns: undefined }
      toggle_message_reaction: {
        Args: { p_emoji: string; p_message_id: string }
        Returns: Json
      }
    }
    Enums: {
      app_role: "admin" | "member"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: ["admin", "member"],
    },
  },
} as const
